  spring:
  config:
    import: classpath:application-config.yml
  datasource:
    url: jdbc:h2:mem:test;MODE=MariaDB;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info
    com:
      web: debug

file:
  path: /data

mail:
  host: smtp.gmail.com
  port: 587
  username: ${GMAIL_USER_EMAIL}
  password: ${GMAIL_APP_PASSWORD}
llm:
  end-point: ${LLM_END_POINT}
car_talk:
  secret: ${TOKEN_SECRET}
